services:
    beetrigged:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ../opencanary/data/:/test/
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - opencanary
        restart: always

    opencanary:
        env_file:
            - .env
        # network_mode: 'host'
        ports:
            - '4555:4555'
        cap_add:
            - NET_ADMIN
        build:
            context: ../opencanary/
            dockerfile: Dockerfile.stable
        restart: always
        volumes:
            - ../opencanary/data/.opencanary.conf:/root/.opencanary.conf
            - /var/log/kern.log:/var/log/kern.log
